apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-manager.fullname" . }}-secrets
  labels:
    {{- include "cloud-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
